" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
try
  source ~/.vim_runtime/my_configs.vim
catch
endtry
execute pathogen#infect()

" Enable syntax Highligting
syntax on

filetype plugin indent on

" Enable Line number
:set number

" Solarized Dark Theme
set termguicolors
set background=dark
colorscheme solarized8



" Vim Plug Plugins
call plug#begin('~/.vim/plugged')
Plug 'lifepillar/vim-solarized8'
call plug#end()
